// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDOd3Blwwvd10RxXWMad6cs5M1ctLxeOo',
    appId: '1:751796429426:web:f1a631f58e91f914ac58eb',
    messagingSenderId: '751796429426',
    projectId: 'mathmind-e5870',
    authDomain: 'mathmind-e5870.firebaseapp.com',
    storageBucket: 'mathmind-e5870.appspot.com',
    measurementId: 'G-X7WFJ8F4BC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ16rNI2b5dmEzlFdoMMUN6P79xiCUr-Q',
    appId: '1:751796429426:android:2a6af2cb208570a7ac58eb',
    messagingSenderId: '751796429426',
    projectId: 'mathmind-e5870',
    storageBucket: 'mathmind-e5870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa5mP1pJ8SYeWb4vSewB_evLmTa3n89YU',
    appId: '1:751796429426:ios:962098caedb50d14ac58eb',
    messagingSenderId: '751796429426',
    projectId: 'mathmind-e5870',
    storageBucket: 'mathmind-e5870.appspot.com',
    iosBundleId: 'com.example.mathmind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa5mP1pJ8SYeWb4vSewB_evLmTa3n89YU',
    appId: '1:751796429426:ios:962098caedb50d14ac58eb',
    messagingSenderId: '751796429426',
    projectId: 'mathmind-e5870',
    storageBucket: 'mathmind-e5870.appspot.com',
    iosBundleId: 'com.example.mathmind',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDOd3Blwwvd10RxXWMad6cs5M1ctLxeOo',
    appId: '1:751796429426:web:fb64563bec8e0e37ac58eb',
    messagingSenderId: '751796429426',
    projectId: 'mathmind-e5870',
    authDomain: 'mathmind-e5870.firebaseapp.com',
    storageBucket: 'mathmind-e5870.appspot.com',
    measurementId: 'G-1QHYT5X2XB',
  );
}
